const orderCreated = {
    id: 39759,
    parent_id: 0,
    status: 'on-hold',
    currency: 'BRL',
    version: '7.1.0',
    prices_include_tax: true,
    date_created: '2022-12-05T18:58:16',
    date_modified: '2022-12-05T18:58:16',
    discount_total: '0.00',
    discount_tax: '0.00',
    shipping_total: '0.00',
    shipping_tax: '0.00',
    cart_tax: '0.00',
    total: '350.00',
    total_tax: '0.00',
    customer_id: 316,
    order_key: 'wc_order_uS0t1iCQ0MaJ5',
    billing: {
      first_name: 'Yuri TESTE',
      last_name: 'Lima TESTE',
      company: '',
      address_1: 'aaaassss',
      address_2: '',
      city: 'aaaaaaa',
      state: 'SC',
      postcode: '88111-320',
      country: 'BR',
      email: 'yuri@innovacestas.com.br',
      phone: '(85) 99685-9001',
      payment: '',
      billing_cpf: '024.903.693-26',
      billing_cnpj: '',
      billing_company: '',
      space: '',
      delivery: '',
      billing_recipient: 'Lima TESTE',
      billing_recipient_phone: '🇧🇷 (85) 99685-9001',
      billing_number: '220',
      billing_complementary: 'aaaaa',
      billing_neighborhood: 'aaaaaa',
      billing_msg: 'asdasd',
      space_2: '',
      number: '220',
      neighborhood: 'aaaaaa',
      persontype: 'F',
      cpf: '02490369326',
      rg: '',
      cnpj: '',
      ie: '',
      birthdate: '',
      sex: '',
      cellphone: ''
    },
    shipping: {
      first_name: '',
      last_name: '',
      company: '',
      address_1: '',
      address_2: '',
      city: '',
      state: '',
      postcode: '',
      country: '',
      phone: '',
      number: '',
      neighborhood: ''
    },
    payment_method: 'bacs',
    payment_method_title: 'PIX ou Transferência <img src="https://innovacestas.com.br/development/wp-content/uploads/2021/10/PIX.png" />',
    transaction_id: '',
    customer_ip_address: '86.42.6.128',
    customer_user_agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
    created_via: 'checkout',
    customer_note: '',
    date_completed: null,
    date_paid: null,
    cart_hash: 'd493ac2d251df130960d5d31ded3ed39',
    number: '39759',
    meta_data: [
      { id: 1114606, key: '_billing_persontype', value: '1' },
      { id: 1114607, key: '_billing_cpf', value: '024.903.693-26' },
      { id: 1114608, key: '_billing_cnpj', value: '' },
      { id: 1114609, key: '_billing_recipient', value: 'Lima TESTE' },
      {
        id: 1114610,
        key: '_billing_recipient_phone',
        value: '🇧🇷 (85) 99685-9001'
      },
      { id: 1114611, key: '_billing_number', value: '220' },
      { id: 1114612, key: '_billing_complementary', value: 'aaaaa' },
      { id: 1114613, key: '_billing_neighborhood', value: 'aaaaaa' },
      { id: 1114614, key: '_billing_msg', value: 'asdasd' },
      { id: 1114615, key: 'is_vat_exempt', value: 'no' },
      { id: 1114616, key: '_thwcfe_ship_to_billing', value: '1' },
      {
        id: 1114617,
        key: '_thwcfe_disabled_fields',
        value: 'time_celebration,delivery_alert'
      },
      { id: 1114618, key: 'billing_cpf', value: '024.903.693-26' },
      { id: 1114619, key: 'billing_recipient', value: 'Lima TESTE' },
      {
        id: 1114620,
        key: 'billing_recipient_phone',
        value: '🇧🇷 (85) 99685-9001'
      },
      { id: 1114621, key: 'billing_number', value: '220' },
      { id: 1114622, key: 'billing_complementary', value: 'aaaaa' },
      { id: 1114623, key: 'billing_neighborhood', value: 'aaaaaa' },
      { id: 1114624, key: 'billing_msg', value: 'asdasd' },
      { id: 1114625, key: 'date', value: '05/12/2022' },
      { id: 1114626, key: 'time', value: 'Horário Comercial' },
      { id: 1114627, key: '_ga_tracked', value: '1' }
    ],
    line_items: [
      {
        id: 21282,
        name: 'Flores Media',
        product_id: 2114,
        variation_id: 0,
        quantity: 1,
        tax_class: '',
        subtotal: '350.00',
        subtotal_tax: '0.00',
        total: '350.00',
        total_tax: '0.00',
        taxes: [],
        meta_data: [],
        sku: '',
        price: 350,
        image: [Object],
        parent_name: null
      }
    ],
    tax_lines: [],
    shipping_lines: [
      {
        id: 21283,
        method_title: 'Frete Grátis',
        method_id: 'free_shipping',
        instance_id: '35',
        total: '0.00',
        total_tax: '0.00',
        taxes: [],
        meta_data: [Array]
      }
    ],
    fee_lines: [],
    coupon_lines: [],
    refunds: [],
    payment_url: 'https://innovacestas.com.br/development/finalizar-compra/order-pay/39759/?pay_for_order=true&key=wc_order_uS0t1iCQ0MaJ5',
    is_editable: true,
    needs_payment: false,
    needs_processing: true,
    date_created_gmt: '2022-12-05T21:58:16',
    date_modified_gmt: '2022-12-05T21:58:16',
    date_completed_gmt: null,
    date_paid_gmt: null,
    schedule: {
      date: '05/12/2022',
      time: 'Horário Comercial',
      time_celebration: '',
      delivery_alert: '',
      space_3: ''
    },
    currency_symbol: 'R$',
    _links: {
      self: [ [Object] ],
      collection: [ [Object] ],
      customer: [ [Object] ]
    }
  }

export default orderCreated