/**
 * @description Generate random numbers of given length using Math.random() function.
 * @details It is a blocking operation and should be avoided.
 * @details2 This function was generated by GitHub Copilot.
 * @param {number} length
 * @returns {string}
 */
function randomNumbersLength(length: number): string {
    let result = "";
    const characters = "0123456789";
    const charactersLength = characters.length;
    for (let i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength)); // It is a blocking operation and should be avoided.
    }
    return result;
}

/**
 * @description Generate random numbers from min to max using Math.random() function.
 * @details It is a blocking operation and should be avoided.
 * @details2 This function was generated by GitHub Copilot.
 */
function randomNumbersRange(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min; // It is a blocking operation and should be avoided.
}

export {
    randomNumbersLength,
    randomNumbersRange
}

